Добавляет разметку главной страницы
htmlacademy-adaptive/1737917-sedona-23 pull request #2
Opened 2021-07-25 05:11 UTC by Bezlpetr

2021-07-25 10:06 UTC, SidSpears69 requested changes

2021-07-25 10:06 UTC, SidSpears69 commented on .editorconfig
> +indent_size = 2
Вернуть к значению по умолчанию!

2021-07-25 10:06 UTC, SidSpears69 commented on source/index.html
> +      <img src="img/icon/logotype-mobile.svg" width="102" height="84" alt="Седона">
Картинкам добавить классы

2021-07-25 10:06 UTC, SidSpears69 commented on source/index.html
> +            <a>
И ссылкам тоже

2021-07-25 10:06 UTC, SidSpears69 commented on source/index.html
> +    <h1>Седона — небольшой городок в Аризоне, заслуживающий большего!</h1>
И заголовкам

2021-07-25 10:06 UTC, SidSpears69 commented on source/index.html
> +            <h3 class="advantages__title">Настоящий городок</h3>
Нарушение БЭМ, блок advantages не существует, есть  блок advantages-list

2021-07-25 11:34 UTC, Bezlpetr commented on .editorconfig
> +indent_size = 2
Я и вернул значение по умолчанию, т.к. в первый пулреквест я эти значения поменял. Правда забыл про [*.md], но сейчас все сверил по первому пудреквесту

2021-07-25 11:40 UTC, Bezlpetr commented on source/index.html
> +      <img src="img/icon/logotype-mobile.svg" width="102" height="84" alt="Седона">
Добавил

2021-07-25 11:43 UTC, Bezlpetr commented on source/index.html
> +            <a>
Добавил

2021-07-25 11:45 UTC, Bezlpetr commented on source/index.html
> +    <h1>Седона — небольшой городок в Аризоне, заслуживающий большего!</h1>
Добавил

2021-07-25 16:30 UTC, Bezlpetr commented on source/index.html
> +            <h3 class="advantages__title">Настоящий городок</h3>
исправил

2021-07-26 14:03 UTC, SidSpears69 commented on source/index.html
> +          <p class="advantages_title">
Элемент должен быть с двумя "__"

2021-07-26 14:04 UTC, merged